---
- hosts: wp_nodes
  become: yes
  vars_files:
    - vars/main.yaml
  tasks:
    - include_tasks: tasks/db.yaml
    - include_tasks: tasks/os.yaml
    - include_tasks: tasks/wp.yaml


    





